# Create a new docker net
docker network create --driver bridge trading-net

#verify
docker network ls

#Build Stage
FROM maven:3.6-jdk-8-slim AS build
COPY src /build/src
COPY pom.xml /build/
RUN mvn -f /build/pom.xml clean package -DskipTests

#Package stage
FROM openjdk:8-alpine
COPY --from=build /build/target/trading-1.0-SNAPSHOT.jar /user/local/app/trading/lib/trading_app.jar
ENTRYPOINT ["java","-jar","/user/local/app/trading/lib/trading_app.jar"]
