package ca.jrvs.apps.trading.controller;

import ca.jrvs.apps.trading.model.domain.Account;
import ca.jrvs.apps.trading.model.domain.Trader;
import ca.jrvs.apps.trading.model.view.TraderAccountView;
import ca.jrvs.apps.trading.service.TraderAccountService;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Date;

@Api(value = "Trader", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
@Controller
@RequestMapping("/trader")
public class TraderAccountController {

    private TraderAccountService traderAccountService;
    @Autowired
    public TraderAccountController(TraderAccountService traderAccountService){
        this.traderAccountService = traderAccountService;

    }

    @ApiOperation(value = "Create a trader and an account.",
            notes = "TraderId and AccountId are auto generated by the database,"
                    + "and they should be identical. Assume each trader has exact one account.")

    @ResponseStatus(HttpStatus.CREATED)
    @ResponseBody
    @PostMapping(
            path = "/firstname/{firstname}/lastname/{lastname}/dob/{dob}/country/{country}/email/{email}",
            produces = {MediaType.APPLICATION_JSON_UTF8_VALUE}
    )
    public TraderAccountView createTrader(@PathVariable String firstname, @PathVariable String lastname, @PathVariable @DateTimeFormat(pattern = "yyyy-mm-dd") Date dob,
                                          @PathVariable String country, @PathVariable String email){
        try{
            Trader trader = new Trader();
            trader.setCountry(country);
            trader.setDob(dob);
            trader.setEmail(email);
            trader.setFirst_name(firstname);
            trader.setLast_name(lastname);
            return traderAccountService.createTraderAndAccount(trader);
        }catch (Exception e){
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }

    @ApiOperation(value = "Create a trader and an account with DTO",
            notes = "TraderId and AccountId are auto generated by the database, and they should be ")
    @ResponseStatus(HttpStatus.CREATED)
    @ResponseBody
    @PostMapping(path = "/", produces = {MediaType.APPLICATION_JSON_UTF8_VALUE})
    public TraderAccountView createTrader(@RequestBody Trader trader){
        try{
            return traderAccountService.createTraderAndAccount(trader);
        }catch (Exception e){
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }

    @ApiOperation(value = "Delete a trader",
            notes = "Delete a trader IFF its account balance is 0 and no open positions."
                    + "Also delete the associated account and securityOrders.")
    @ApiResponses(value = {@ApiResponse(code = 400, message = "Unable to delete the user")})
    @DeleteMapping(path = "/traderId/{traderId}")
    @ResponseStatus(HttpStatus.OK)
    public void deleteTrader(@PathVariable Integer traderId){
        try{
            traderAccountService.deleteTraderById(traderId);
        }catch (Exception e){
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }

    @ApiOperation(value = "Deposit a fund",
            notes = "Deposit fund to the account associated with the given traderId.")
    @ApiResponses(value = {
            @ApiResponse(code = 404, message = "traderId is not found"),
            @ApiResponse(code = 400, message = "unable to deposit due to user input")})
    @ResponseStatus(HttpStatus.OK)
    @ResponseBody
    @PutMapping(path = "/withdrwa/traderId/{traderId}/amount/{amount}")
    public Account depositFund(@PathVariable Integer traderId, @PathVariable Double amount){
        try{
            return traderAccountService.deposit(traderId,amount);
        }catch (Exception e){
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }

    }
    @ApiOperation(value = "Withdraw a fund",
            notes = "Withdraw fund to the account associates with the given traderId.")
    @ApiResponses(value = {
            @ApiResponse(code = 404, message = "traderId is not found"),
            @ApiResponse(code = 400, message = "Unable to withdraw due to user input")})
    @ResponseStatus(HttpStatus.OK)
    @ResponseBody
    @PutMapping(path = "/withdrwa/traderId/{traderId}/amount/{amount}")
    public Account withdrawFund(@PathVariable Integer traderId, @PathVariable Double amount){
        try{
            return traderAccountService.withdraw(traderId,amount);
        }catch (Exception e){
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }




}
